#!/bin/sh
if [ "$1" == "-h" ]; then
	cat <<END
sjmpv can be called with two different kind of way:

Option #1:
sjmpv mainfile.mp4

This way it will start the "main" player

Option #2:
sjmpv /soundtrack/directory

This way it will start the "soundtrack" player

The difference between the main player and the soundtrack player, that:
- The two listens on two different ipc sockets
- The soundtrack player will play the directory shuffled, and with -vo null
END
	exit 0
fi
if [ -d "$1" ]; then
	exec mpv --input-ipc-server=~~/st.sock -shuffle -vo null "$@"
else
	fn="${1%.mp4}"
	fn="${fn%_??s4}"
	export SJSTFILE="${fn}_soundtrack.txt"
	exec mpv --input-ipc-server=~~/main.sock "$1"
fi
